openapi: '3.0.0'

info:
  title: Task Management API
  version: 0.0.0
  description:
    $ref: 'description.yml#/introduction'
  license:
    name: none
    url: none

servers:
  - url: 'http://api-dev.taskmanagement.com'
    description: development
  - url: 'https://api-preview.taskmanagement.com'
    description: production preview
  - url: 'https://api.taskmanagement.com'
    description: production

tags:
  - name: Authentication
    description: |-
      API endpoints that helps you Sign up, Login, Logout, etc. and actions related to authentication and authorization.

  - name: Users
    description: |
      Provides logged in user information and required endpoints to alter user data i.e. update profile, change password, delete account, etc.

paths:
  $ref: './paths.yml'

components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
      description: |
        ## OAuth Authentication

        In order to interact with the DigitalOcean API, you or your application must
        authenticate.

        The DigitalOcean API handles this through OAuth, an open standard for
        authorization. OAuth allows you to delegate access to your account.
        Scopes can be used to grant full access, read-only access, or access to
        a specific set of endpoints.

        You can generate an OAuth token by visiting the [Apps & API](https://cloud.digitalocean.com/account/api/tokens)
        section of the DigitalOcean control panel for your account.

        An OAuth token functions as a complete authentication request. In effect, it
        acts as a substitute for a username and password pair.

        Because of this, it is absolutely **essential** that you keep your OAuth
        tokens secure. In fact, upon generation, the web interface will only display
        each token a single time in order to prevent the token from being compromised.

        DigitalOcean access tokens begin with an identifiable prefix in order to
        distinguish them from other similar tokens.

        - `dop_v1_` for personal access tokens generated in the control panel
        - `doo_v1_` for tokens generated by applications using [the OAuth flow](https://docs.digitalocean.com/reference/api/oauth-api/)
        - `dor_v1_` for OAuth refresh tokens

        ### Scopes

        Scopes act like permissions assigned to an API token. These permissions
        determine what actions the token can perform. You can create API
        tokens that grant read-only access, full access, or limited access to
        specific endpoints by using custom scopes.

        Generally, scopes are designed to match HTTP verbs and common CRUD
        operations (Create, Read, Update, Delete).

        | HTTP Verb | CRUD Operation | Scope |
        |---|---|---|
        | GET | Read | `<resource>:read` |
        | POST | Create | `<resource>:create` |
        | PUT/PATCH | Update | `<resource>:update` |
        | DELETE | Delete | `<resource>:delete` |

        For example, creating a new Droplet by making a `POST` request to the
        `/v2/droplets` endpoint requires the `droplet:create` scope while
        listing Droplets by making a `GET` request to the `/v2/droplets`
        endpoint requires the `droplet:read` scope.

        Each endpoint below specifies which scope is required to access it when
        using custom scopes.

        ### How to Authenticate with OAuth

        In order to make an authenticated request, include a bearer-type
        `Authorization` header containing your OAuth token. All requests must be
        made over HTTPS.

        ### Authenticate with a Bearer Authorization Header

        ```
        curl -X $HTTP_METHOD -H "Authorization: Bearer $DIGITALOCEAN_TOKEN" "https://api.digitalocean.com/v2/$OBJECT"
        ```
